version: 2
mergeable:
  - when: "pull_request.*, pull_request_review.*"
    name: "check if employee or signed copyright waiver"
    validate:
      - do: author
        and:
          - team: '@tipi-oss-testing/employees'
          - team: '@tipi-oss-testing/contributor-signed-copyright-waiver'
  - when: "pull_request.*, pull_request_review.*"
    name: "check reasoning given"
    #filter:
    validate:
      - do: title
        must_include:
          regex: 'doc|feat|fix|chore'
          regex_flag: 'i' # case insensitive
          message: 'Specify the reason for this merge'
        must_exclude:
          regex: 'DO NOT MERGE|WIP'
          regex_flag: 'none' # Optional. Specify the flag for Regex. default is 'i', to disable default use 'none'
          message: 'Marked as work in progress'
      - do: description
        no_empty:
          enabled: true
          message: "Description matter and must not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed."
